### ISSUE TITLE
Postal Code: data is not up-to-date

### ISSUE THREAD

**Issue by htdat** [daohoangson/dvhcvn#10]
https://github.com/daohoangson/dvhcvn/blob/master/data/sorted.json
I know this is WIP https://github.com/daohoangson/dvhcvn/pull/7

However, the source of data may not be correct? 

For example: `50408` is for P. Phước Mỹ - Sơn Trà - Đà Nẵng. 
Source: http://dmdc.ngsp.gov.vn/WebPortal/Detail?CategoryId=85e7cbfa-40ed-4379-b010-943a31e5c898&ValueId=ac43ba8c-63f0-4bd3-948b-ff4ce19a15d4&ParrentPageRedirect=1&PageIndex=0

Another source: http://mabuuchinh.vn/default.aspx?page=SearchMBC

sorted.json file above is showing: 

```json
                    ["20275", "Phước Mỹ", "Phường", "Phuoc My"],

```

**Comment by daohoangson** [comment]
The postcode data is not ready so it's in its own file. Also, the branch is not merged yet so it is currently here:

https://github.com/daohoangson/dvhcvn/blob/postcode/data/postcode.json

20275 is the administrative unit ID. You will find the postcode by looking for that ID.

![Screen Shot 2020-09-06 at 4 26 42 PM](https://user-images.githubusercontent.com/239336/92322821-c242bd80-f05d-11ea-8dea-294665211421.jpg)

-> postcode for ID 20275 (Phường Phước Mỹ) is 50408.

I have some clean up to do. Afterwards, postcode will be included in the `sorted.json` file.

**Comment by htdat** [comment]
Aha, that makes sense!
