### ISSUE TITLE
https://www.gso.gov.vn/dmhc2015/ no longer works

### ISSUE THREAD

**Issue by daohoangson** [daohoangson/dvhcvn#11]
![photo_2020-11-03 09 00 15](https://user-images.githubusercontent.com/239336/97938067-024ec400-1db3-11eb-827e-83acfd85a056.jpeg)

**Comment by daohoangson** [comment]
Deleted Cloud Scheduler job.

**Comment by Ihsara** [comment]
https://www.gso.gov.vn/phuong-phap-thong-ke/danh-muc/don-vi-hanh-chinh/
Is this the new one that you need?

**Comment by daohoangson** [comment]
Great find. I think this is it! https://danhmuchanhchinh.gso.gov.vn/
