### ISSUE TITLE
Missing a lot of administrative units

### ISSUE THREAD

**Issue by heraclex12** [daohoangson/dvhcvn#21]
Hi,

I find there are a lot of administrative units (e.g., Thị trấn Hòa Thành/Hòa Thành/Tây Ninh, Tân Thành/Bà Rịa - Vũng Tàu,...) not existing in `data` folder.

**Comment by daohoangson** [comment]
They have been renamed / moved.

`Thị trấn Hòa Thành/Hòa Thành/Tây Ninh` -> `Phường Long Hoa, Thị xã Hòa Thành`

Source [thanhnien.vn](https://thanhnien.vn/tay-ninh-chinh-thuc-co-them-2-thi-xa-la-hoa-thanh-va-trang-bang-post930011.html), [dvhcvn/data](https://github.com/dvhcvn/data/blob/91334c4cfb4a45b56c4740889e337304144a9e74/tree.json#L20419-L20422).

`Tân Thành/Bà Rịa - Vũng Tàu` -> `Thị xã Phú Mỹ`

Source [baobariavungtau.com.vn](https://baobariavungtau.com.vn/kinh-te/201805/ngay-18-5-tan-thanh-chinh-thuc-tro-thanh-thi-xa-phu-my-794875/), [dvhcvn/data](https://github.com/dvhcvn/data/blob/91334c4cfb4a45b56c4740889e337304144a9e74/tree.json#L21213-L21216).

**Comment by heraclex12** [comment]
Ok gotcha. Thank you for letting me know.
