### ISSUE TITLE
Null-safety migration

### ISSUE THREAD

**Issue by definev** [daohoangson/dvhcvn#22]
Mong anh update lên null-safety cho dart package

**Comment by daohoangson** [comment]
Thank you for the suggestion.

**Comment by daohoangson** [comment]
I noticed you have migrated it on your fork. Unfortunately the package is code generated so I cannot merge your change. Can you refactor the generator itself?

https://github.com/daohoangson/dvhcvn/blob/master/transformers/dart-dvhcvn/bin/generate.dart

**Comment by definev** [comment]
I think we don't need change `generate.dart`, the previous generated code is work perfect with my migration the thing need to change is `Entity` class and the child class.
