### ISSUE TITLE
thiếu thông tin

### ISSUE THREAD

**Issue by huynv86** [daohoangson/dvhcvn#24]
Cuối năm [2019](https://vi.wikipedia.org/wiki/2019), huyện Lý Sơn có 3 đơn vị hành chính trực thuộc, gồm các xã: An Bình, An Vĩnh và An Hải.

mình chưa kiểm tra hết, ko rõ ngoài 3 xã trên còn thiếu gì ko

**Comment by huynv86** [comment]
3 xã này đã giải thể

**Comment by daohoangson** [comment]
Uh, đúng là 3 xã này đã bị xóa khỏi dữ liệu. Bạn có thể tham khảo thêm tại đây:

https://github.com/dvhcvn/data/blob/91334c4cfb4a45b56c4740889e337304144a9e74/tree.json#L17354-L17373

<img width="239" alt="Screen Shot 2022-02-06 at 09 11 47" src="https://user-images.githubusercontent.com/239336/152665353-d3b8919c-abf1-422c-9d88-2946afc440da.png">
