### ISSUE TITLE
Bản đồ hành chính của các tỉnh thành

### ISSUE THREAD

**Issue by hiep85** [daohoangson/dvhcvn#25]
Mình muốn xin dữ liệu để tạo một file geojson đơn vị hành chính của 1 tỉnh, thành phố cụ thể như Hà Nội, Hồ Chí Minh thì làm như thế nào?
Cảm ơn các bạn.

**Comment by daohoangson** [comment]
Bạn xem ở đây nha https://github.com/daohoangson/dvhcvn/tree/master/data/gis. Tên file là mã tỉnh / thành phố, ví dụ Hà Nội thì là `01.json`.

**Comment by hiep85** [comment]
> Bạn xem ở đây nha https://github.com/daohoangson/dvhcvn/tree/master/data/gis. Tên file là mã tỉnh / thành phố, ví dụ Hà Nội thì là `01.json`.

Cảm ơn bạn đã trả lời mình. Mình cũng thử tải file 01.json của Hà Nội nhưng khi up lên mapshaper thì chỉ nhận được địa giới của Hà Nội chứ không có quận huyện hay phường xã. Mình chưa hiểu làm cách nào để tạo một file bản đồ hành chính của 1 địa phương, ví dụ là Hà Nội?

Mình cảm ơn.

**Comment by daohoangson** [comment]
Do trong gis json nó có cái key `level2s` là các quận / huyện nên bạn phải tự mapping để tool nó nhận được.

**Comment by hiep85** [comment]
> 
Cảm ơn bạn, bạn có thể giới thiệu cho mình xin một tip hướng hoặc phần mềm để làm việc đó được không? Xin lỗi vì đã làm phiền do mình không phải là một dev, nhưng mình rất muốn tìm hiểu.

**Comment by daohoangson** [comment]
Cái này phụ thuộc vào tool bạn xài thôi, ví dụ bạn xài mapshaper (có phải là https://mapshaper.org không?) thì bạn cần sửa cái file json cho đúng định dạng mà nó hiểu thì mới hiển thị được.

- Mình xem qua home page của tool thì thấy hỗ trợ GeoJSON tức là cái file json mà có key `coordinates` thì nó sẽ hiểu.
- Trong file `01.json` thì có key đó nên nó vẽ được area của Hà Nội, tuy nhiên mấy cái phường nằm trong key `level2s` thì nó không hiểu nên không vẽ được.
- Nếu bạn muốn vẽ luôn thì phải copy từng phường ra file riêng (mỗi phường có `coordinates` riêng sẵn rồi).

**Comment by hiep85** [comment]
> Cái này phụ thuộc vào tool bạn xài thôi, ví dụ bạn xài mapshaper (có phải là https://mapshaper.org không?) thì bạn cần sửa cái file json cho đúng định dạng mà nó hiểu thì mới hiển thị được.
> 
> * Mình xem qua home page của tool thì thấy hỗ trợ GeoJSON tức là cái file json mà có key `coordinates` thì nó sẽ hiểu.
> * Trong file `01.json` thì có key đó nên nó vẽ được area của Hà Nội, tuy nhiên mấy cái phường nằm trong key `level2s` thì nó không hiểu nên không vẽ được.
> * Nếu bạn muốn vẽ luôn thì phải copy từng phường ra file riêng (mỗi phường có `coordinates` riêng sẵn rồi).

Cảm ơn bạn đã hỗ trợ nhé. Mình sẽ thử làm theo hướng dẫn.
