### ISSUE TITLE
Website không truy cập được

### ISSUE THREAD

**Issue by ooker777** [daohoangson/dvhcvn#98]
Vào https://dvhcvn.vercel.app/ thì gặp lỗi:
```
404: NOT_FOUND Code: NOT_FOUND ID: sin1::z8gcr-1728915896731-fae47f0ebf19
```
Tuy nhiên API vẫn chạy được.

**Comment by daohoangson** [comment]
Do không có trang index nên nó bị 404, chắc để tạm cái redirect về lại GitHub :D
